### PR TITLE
Migrate remaining mail actions to the durable outbox

### PR DESCRIPTION
**Pull request by elie222**
> ❌ **Browser QA failed** · [QA report](https://qa.getinboxzero.com/20260826-092645_pr-3392_748182c2ffcb/report.html)
>
> <sub>Apply `rerun-qa` to rerun.</sub>

## Summary

- replace the legacy account-unsafe localStorage mail queues with atomic, account-scoped IndexedDB batches using exact thread/message snapshots
- migrate EmailList, CommandK, sender bulk actions, and bulk-unsubscribe deletion to the durable outbox; preserve Gmail archive labels and remove the obsolete queue initializer
- reconcile each durable batch with one restart-safe mailbox sync, retain optimistic overlays until refresh succeeds, and restore active sender status/progress across reloads with failures reported separately

## Testing

- `RUN_AI_TESTS=false pnpm exec vitest --run --maxWorkers=4` — 772 files: 5,832 passed, 766 skipped
- focused durable-mail suite — 16 files, 167 tests passed
- `pnpm check` — passed with existing repository warnings only
- `git diff --check`

<a href="https://cubic.dev/pr/elie222/inbox-zero/pull/3392?utm_source=github" target="_blank" rel="noopener noreferrer" data-no-image-dialog="true"><picture><source media="(prefers-color-scheme: dark)" srcset="https://www.cubic.dev/buttons/review-in-cubic-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://www.cubic.dev/buttons/review-in-cubic-light.svg">Review in cubic</picture></a>

## Summary by CodeRabbit

* **New Features**
  * Mail actions now use durable batches for archiving, trashing, and marking messages as read.
  * Archive actions can preserve selected labels.
  * Sender-based actions process all matching threads reliably.
  * Progress panels show active, settled, and failed work.

* **Bug Fixes**
  * Failed bulk operations are no longer reported as successful.
  * Mail updates remain visible while synchronization completes.
  * Improved recovery and retry handling for storage and provider failures.
  * Command palette archiving now handles loading and errors more reliably.
  * Bulk actions continue processing remaining items after individual failures.
  * Legacy queued actions are cleaned up automatically.

### CODE REVIEW

File: apps/web/app/(app)/[emailAccountId]/bulk-unsubscribe/ArchiveProgress.tsx [hunk 1]
```diff
@@ -1,55 +1,31 @@
...
-      itemLabel="emails"
+      totalItems={totalItems}
+      remainingItems={activeItems}
+      inProgressText={`Archiving senders...${failedItems ? ` ${failedItems} failed.` : ""}`}
+      completedText={
+        failedItems
+          ? `Archiving finished: ${completedItems} succeeded, ${failedItems} failed.`
+          : "Archiving complete!"
+      }
+      itemLabel="senders"
```
[the remark this answers is not in the document]
Comment (elie222) [reply apps/web/app/(app)/[emailAccountId]/bulk-unsubscribe/ArchiveProgress.tsx:40]: Fixed in 8abe57d01. Settled archive progress now clears the account-scoped sender status after the existing three-second completion window, with a regression test.

File: apps/web/app/(app)/[emailAccountId]/bulk-unsubscribe/hooks.ts [hunk 2]
```diff
@@ -903,41 +901,35 @@ async function deleteAllFromSender({
...
-          ? `Deleting ${data} emails from ${name}...`
-          : `No emails to delete from ${name}`,
-      error: `There was an error deleting the emails from ${name} :(`,
-    },
-  );
+  try {
+    return await deletion;
+  } finally {
+    onFinish();
+  }
```
[the remark this answers is not in the document]
Comment (elie222) [reply apps/web/app/(app)/[emailAccountId]/bulk-unsubscribe/hooks.ts:932]: Fixed in 8abe57d01. The delete-all handler now catches and reports the rejection while the existing finally path still clears loading state; the failure path is covered by a test.

File: apps/web/app/(app)/MailMutationOutboxManager.tsx [hunk 3]
```diff
@@ -207,6 +238,40 @@ async function processMutation(mutation: MailMutation, ownerId: string) {
...
+  const delay = Math.min(1000 * 2 ** Math.max(0, attempts - 1), 60_000);
+  await retryMailMutationSyncGroup(
+    group,
+    {
+      error: "Mailbox reconciliation failed",
+      nextAttemptAt: Date.now() + delay,
+    },
+    ownerId,
+  );
+}
```
[the remark this answers is not in the document]
Comment (elie222) [reply apps/web/app/(app)/MailMutationOutboxManager.tsx:273]: Fixed in 8abe57d01. Reconciliation now persists and increments a separate syncAttempts counter, and retry backoff uses it across reloads (1s/2s/4s up to 60s). Added claim/reclaim and manager backoff regressions.

File: apps/web/components/CommandK.tsx [hunk 4]
```diff
@@ -99,12 +105,23 @@ function CommandPaletteContent({
...
+                threads: [displayedThread.thread],
+              });
+              showEmail(null);
+            } catch {
+              toastError({
+                description: "Couldn't queue archiving this email",
+              });
+            }
+          }
+        : undefined,
```
[the remark this answers is not in the document]
Comment (elie222) [reply apps/web/components/CommandK.tsx]: Fixed in 8abe57d01. The archive shortcut stays bound while a thread snapshot is loading or unavailable and gives explicit feedback without queuing an incomplete snapshot. Covered by CommandK tests.

File: apps/web/components/email-list/EmailList.tsx [hunk 5]
```diff
@@ -156,12 +156,32 @@ export function EmailList({
...
+    () =>
+      mutationOverlayReady
+        ? applyMailMutationOverlayToThreads({
+            getEmailAccountId: () => emailAccountId,
+            mutations,
+            threads: sourceThreads,
+          })
+        : [],
+    [emailAccountId, mutationOverlayReady, mutations, sourceThreads],
+  );
```
[the remark this answers is not in the document]
Comment (elie222) [reply apps/web/components/email-list/EmailList.tsx:185]: Fixed in 8abe57d01. EmailList renders no empty state until the mutation overlay is ready; the normal empty state remains unchanged afterward. Added a regression test.

**Comment by elie222** [comment]
Addressed the remaining outside-diff/nitpick review items in 8abe57d01: sender batches continue after individual enqueue failures, already-read rows skip redundant read mutations, retained-overlay reconciliation no longer mutates state during render, active-status classification is shared, and sync-group ordering no longer uses non-null assertions. The combined focused regression suite passes 168 tests.

**Comment by elie222** [comment]
Addressed the latest re-review findings in 92e27db71: `EmailList` no longer accepts a default no-op refetch, so retained mutations can only clear after an actual async source refresh; sync-group tests now explicitly guard optional claims instead of using non-null assertions. Focused validation passes 35 tests and `pnpm check` remains clean apart from existing repository warnings.

**Comment by elie222** [comment]
Fixed the Web E2E regression in 6e0a8fb8c. The durable sender batch correctly waited for mailbox reconciliation, but the Google emulator does not implement the mailbox history endpoint; the cleanup spec now stubs only that incremental-sync boundary while still exercising the real archive action and verifying the provider-backed mail result. The focused flow passes locally (2/2), and the exact-head CI is now fully green: build, full tests, Web E2E, security, and CodeRabbit. No actionable comments remain.
